### ISSUE TITLE
pending confirmation --> pending transaction

### ISSUE THREAD

**Issue by ggs134** [Onther-Tech/dashboard.tokamak.network#12]
![pending transaction](https://user-images.githubusercontent.com/8215282/76595440-f7eb6b80-653e-11ea-90f8-1b368611dadc.PNG)

pending confirmation?

--> pending for confirmation
or
--> pending transaction. waiting to be confirmed...

**Comment by thomashin** [comment]
![image](https://user-images.githubusercontent.com/20399507/76716503-c60f1a80-6773-11ea-9898-32e1f6ca6cfc.png)
