### ISSUE TITLE
Can't find `list of requests`(partial request process)

### ISSUE THREAD

**Issue by ggs134** [Onther-Tech/dashboard.tokamak.network#14]
![partial requests](https://user-images.githubusercontent.com/8215282/76596162-ca9fbd00-6540-11ea-9392-e633bceed75c.PNG)

If somebody want to process request partially, how he/she can do that?
Interface required.

**Comment by thomashin** [comment]
DepositManager.sol
```javascript
function processRequests(address rootchain, uint256 n, bool receiveTON) external returns (bool) {
  for (uint256 i = 0; i < n; i++) {
    require(_processRequest(rootchain, receiveTON));
  }
  return true;
}
```
```javascript
function _processRequest(address rootchain, bool receiveTON) internal returns (bool) {
  uint256 index = _withdrawalRequestIndex[rootchain][msg.sender];
  ...
}
```

we can only process requests in sequence. so user can't select request separately. user only choose the number of request to be processed.

**Comment by thomashin** [comment]
we will use `userPendingRequests` and `userWithdrawableRequests`
