### ISSUE TITLE
<Connecting Faraday Testnet Guide> Required

### ISSUE THREAD

**Issue by ggs134** [Onther-Tech/dashboard.tokamak.network#15]
Related issues : https://github.com/Onther-Tech/dashboard.tokamak.network/issues/6

Blog or Slide is a good option.
A better option is to make `automated guide document` whenever endpoint of network changes.

**Comment by thomashin** [comment]
process to connect faraday network is so simple. user just need to set endpoint to faraday network.

![image](https://user-images.githubusercontent.com/20399507/77878113-7dd31a80-7292-11ea-89fe-2d8b1733c219.png)

- Install metamask (if not installed)
- Select network
- Add network
  - network name: Faraday (recommended)
  - RPC url: https://api.faraday.tokamak.network (can be changed)

**Comment by khk77** [comment]
https://medium.com/onther-tech/how-to-add-mton-to-metamask-myetherwallet-fa1580961639

**Comment by thomashin** [comment]
don't need document about how to connect faraday network. because we'll use mainnet.
