### ISSUE TITLE
server: filter root chain address

### ISSUE THREAD

**Issue by 4000D** [Onther-Tech/dashboard.tokamak.network#22]
`POST /operators` must not accept duplicate root chain address.

**Comment by thomashin** [comment]
If it receives duplicate root chain address, should it overwrites?

**Comment by 4000D** [comment]
prevent the duplicate request

**Comment by thomashin** [comment]
we need more validation codes.

**Comment by 4000D** [comment]
yes. check ethereum address validity by web3 (+ also checksum if all alphabets are not lower case)

**Comment by thomashin** [comment]
check checksum like https://github.com/Onther-Tech/dashboard.tokamak.network/blob/70f14174e5adbd0ee3dfa4458e2184a9b72ac149/server/routes/operators.js#L19-L24

**Comment by 4000D** [comment]
duplication not applied

**Comment by thomashin** [comment]
https://github.com/Onther-Tech/dashboard.tokamak.network/blob/17afb60f621b1093856466dfb85ddddaac0474d0/server/routes/operators.js#L30-L33

already implemented.

I forgot that.
