### ISSUE TITLE
Have same withdrawalRequestIndex after withdrawal request

### ISSUE THREAD

**Issue by thomashin** [Onther-Tech/dashboard.tokamak.network#24]
![image](https://user-images.githubusercontent.com/20399507/77031990-8c921580-69e6-11ea-97f4-8e141688c066.png)
- initial value (withdrawalRequestIndex: 0)
- after withdrawal request (withdrawalRequestIndex: 0)

reverted, when I try to get `request` with 0 withdrawalRequestIndex (initial value).

this issue doesn't happen when there is at least one withdrawal request.

**Comment by 4000D** [comment]
What I told is "read numRequest" before "numPendingRequest"

**Comment by 4000D** [comment]
`getRequest` fetch pending requests, which means you don't need to filter them with `getPendingRequests`

**Comment by thomashin** [comment]
I need to filter pending requests depending on `withdrawal delay`
- not withdrawable requests
- withdrawable requests

I think I have to fix function name.

**Comment by thomashin** [comment]
and `numRequest` and `numPendingRequest` values are always the same.

**Comment by 4000D** [comment]
`DepositManager.numRequests` and `DepositManager.numPendingRequests` doesn't always return same value. it depends on `_withdrawalRequestIndex[rootchain][account]`: see [here](https://github.com/Onther-Tech/plasma-evm-contracts/blob/a7590e0946f19ec896fc16cf85cd78306e3d1de8/contracts/stake/managers/DepositManager.sol#L256-L267).

BTW, I think sync concepts and variable names in JavaScript (not HTML) with contracts for [those functions](https://github.com/Onther-Tech/dashboard.tokamak.network/blob/develop/src/store/index.js#L279-L306).
- getRequests -> getPendingRequests
- getPendingRequests -> filterNotWithdrawableRequests
- getWithdrawableRequests -> filterWithdrawableRequests

Also, [contracts](https://github.com/Onther-Tech/plasma-evm-contracts/blob/a7590e0946f19ec896fc16cf85cd78306e3d1de8/contracts/stake/managers/DepositManager.sol#L218) check withdrawable by `r.withdrawableBlockNumber <= block.number`, where equal case is not considered in [JS](https://github.com/Onther-Tech/dashboard.tokamak.network/blob/develop/src/store/index.js#L305) (`request.withdrawableBlockNumber) < currentBlockNumber`)

**Comment by thomashin** [comment]
thanks.

I think we don't need numRequest value. only numPendingRequests variable is enough.

**Comment by 4000D** [comment]
https://github.com/Onther-Tech/dashboard.tokamak.network/commit/17afb60f621b1093856466dfb85ddddaac0474d0#diff-e3b1ca4ad5a207c170c97a435b3d1ff3R305

Equality check is not changed yet.

**Comment by 4000D** [comment]
well, let's discuss this in another issue
