### ISSUE TITLE
withdrawable pending request check

### ISSUE THREAD

**Issue by 4000D** [Onther-Tech/dashboard.tokamak.network#30]
[contracts](https://github.com/Onther-Tech/plasma-evm-contracts/blob/a7590e0946f19ec896fc16cf85cd78306e3d1de8/contracts/stake/managers/DepositManager.sol#L218) check withdrawable by `r.withdrawableBlockNumber <= block.number`, where equal case is not considered in [JS](https://github.com/Onther-Tech/dashboard.tokamak.network/blob/develop/src/store/index.js#L305) (`request.withdrawableBlockNumber) < currentBlockNumber`)

_Originally posted by @4000D in https://github.com/Onther-Tech/dashboard.tokamak.network/issues/24#issuecomment-603636939_

**Comment by thomashin** [comment]
sorry I missed that. thanks.
