### ISSUE TITLE
Deploy at dashboard.tokamak.network

### ISSUE THREAD

**Issue by thomashin** [Onther-Tech/dashboard.tokamak.network#41]
- [x] address and transaction hash link
- [x] title and logo
- [x] zeit url
- [ ] prepare FAUCET / FAQs contents

**Comment by thomashin** [comment]
https://dashboard.faraday.tokamak.network/#/ -> https://dashboard.tokamak.network/#/

and must be reflected at `zeit`

**Comment by sifnoc** [comment]
Noticed, will be update this at [docs/staking-mainnet](https://github.com/Onther-Tech/docs.tokamak.network/tree/docs/staking-mainnet)

**Comment by thomashin** [comment]
need logo and title

**Comment by thomashin** [comment]
default: etherscan
-> from config file

**Comment by thomashin** [comment]
pending (front)

**Comment by thomashin** [comment]
delete `|`
: https://github.com/Onther-Tech/dashboard.tokamak.network/commit/e1cc6cb0593f0365b34ad4c51e7d89f438584df2
