### ISSUE TITLE
Have to connect web3 to our own node

### ISSUE THREAD

**Issue by thomashin** [Onther-Tech/dashboard.tokamak.network#45]
![image](https://user-images.githubusercontent.com/20399507/77977257-28524880-733a-11ea-95ea-fdbfa4821b33.png)
- reference: https://github.com/MetaMask/metamask-extension/issues/7234

metamask has to be used for only signing.

**Comment by 4000D** [comment]
plz specify the background (network, rpc node (infura, ganache, or anything). why is this issue related to our node? did you get this error when using infura? or ganache? or go-ethereum?

**Comment by thomashin** [comment]
error happened this method
https://github.com/Onther-Tech/dashboard.tokamak.network/blob/ea4135da83945c595851bc1aae7e95dc85e7befe/src/store/index.js#L281-L282

background
- metamask web3

So I think this issue related with metamask background, not our implementing.

summary:
- current: contract's call function has been called through metamask's web3
- **to change: through our own node's web3**

**Comment by thomashin** [comment]
other contract's call() also make error. originally these error didn't happen.

**Comment by thomashin** [comment]
I think this is infura issue. because metamask use infura node.

**Comment by thomashin** [comment]
not infura issue. bacause we has been connected to localhost

**Comment by thomashin** [comment]
now preview works. so it is not metamask issue. this may be local node issue.

**Comment by thomashin** [comment]
after go-ethereum restart, it works.

**Comment by thomashin** [comment]
I think due to intensive call to metamask, this issue happened.
