### ISSUE TITLE
metamask endpoint: http://13.209.8.190:8545 doesn't work

### ISSUE THREAD

**Issue by ggs134** [Onther-Tech/dashboard.tokamak.network#5]
![image](https://user-images.githubusercontent.com/8215282/76561085-ee81e500-64e5-11ea-8607-d1c1d8625bd4.png)

**Comment by thomashin** [comment]
This is not bug(precisely my mistake). this happens when blockchain gets shut down. so we can't connect to metamask.

now 13.209.8.190:8545 works, but we have to use stablized network. (like `faraday.tokamak.network`)
