### ISSUE TITLE
add commission rate input field

### ISSUE THREAD

**Issue by 4000D** [Onther-Tech/dashboard.tokamak.network#52]
Onther-Tech/plasma-evm-contracts#18 supports commission rates. So users have to be able to check each operator's commission rates and operator update their commission rates.

the validity of `commissionRate` is checked by

```solidity
(commissionRate == 0) ||
      (MIN_VALID_COMMISSION_RATE <= commissionRate &&
       commissionRate <= MAX_VALID_COMMISSION_RATE)
```

where

```solidity
MAX_VALID_COMMISSION_RATE = 10 ** 27; // 1 RAY
MIN_VALID_COMMISSION_RATE = 10 ** 25; // 0.01 RAY
```

**Comment by thomashin** [comment]
needs to update contract ABI

TODO (_pending_):
- input tag in operator edit layout
- display operator table

**Comment by thomashin** [comment]
![image](https://user-images.githubusercontent.com/20399507/82779915-709c6b80-9e90-11ea-8fa0-6408f46b44a0.png)
