### ISSUE TITLE
Need `genesis.json` file downloader

### ISSUE THREAD

**Issue by thomashin** [Onther-Tech/dashboard.tokamak.network#53]
user node needs operator's `genesis.json` file

**Comment by sifnoc** [comment]
For initialize, yes. but not actually need file.

`geth init` accept via `http`.

Might be dashbaord api can serve it.

If it will serve as like `/genesis?<rootchain addr>`.

**Comment by thomashin** [comment]
GET: http://localhost:9000/genesis?rootchain=0xC4BF071B54914221cC047F480293231E7DF9F85B

**Comment by sifnoc** [comment]
Well worked with this command
```
build/bin/geth init https://dashboard-api.faraday.tokamak.network/genesis?rootchain=0x8Bb208b42B2d1dA1606B3E06ad6648514b6aE080  --rootchain.url ws://52.198.169.75:8546
```

If no contract code exist on rootchain, It will output like below.

`Fatal: Failed to get operator address: no contract code at given address`
