### ISSUE TITLE
Undefined `abi` error

### ISSUE THREAD

**Issue by thomashin** [Onther-Tech/dashboard.tokamak.network#54]
related with `hoisting`?

**Comment by thomashin** [comment]
![image](https://user-images.githubusercontent.com/20399507/78224664-e248e080-7503-11ea-87c3-0dd3d8e19926.png)

**Comment by sifnoc** [comment]
Confirmed, same issue to me.

**Comment by thomashin** [comment]
this issue related with `circular dependencies`

https://stackoverflow.com/questions/37515816/es6-modules-imported-constants-are-undefined-at-first-they-become-available-la

**Comment by thomashin** [comment]
+ use only ABI field (in compiled JSON file from truffle)

**Comment by thomashin** [comment]
I guess importing json file might be optimized from webpack

**Comment by thomashin** [comment]
0685ca7 not fixed

**Comment by thomashin** [comment]
we can't find `circular dependencies`. 

code: https://github.com/Onther-Tech/dashboard.tokamak.network/blob/b33c2447ac20b1897863ae87801bab688d6c6298/src/madge.js

there is no `circular dependencies`.
![image](https://user-images.githubusercontent.com/20399507/78517463-56cb9a00-77f8-11ea-8289-02338f064cc6.png)

**Comment by thomashin** [comment]
summary
1. use abiParser (so we only use abi property)
2. there is no circular dependencies.

I guess that this issue related with now preview.

**Comment by thomashin** [comment]
#61
