### ISSUE TITLE
api: support GET /chainids

### ISSUE THREAD

**Issue by 4000D** [Onther-Tech/dashboard.tokamak.network#55]
related: https://github.com/Onther-Tech/plasma-evm/issues/109

To make a new plasma chain without already used chain id, api server have to provide already used chain ids list.

**Comment by 4000D** [comment]
GET /chainids also supports already known chain ids (ethereum mainnet, ropsten, etc...)

**Comment by 4000D** [comment]
references
https://github.com/ethereum/EIPs/blob/master/EIPS/eip-155.md#list-of-chain-ids
https://ethereum.stackexchange.com/a/17101
https://medium.com/@piyopiyo/list-of-ethereums-major-network-and-chain-ids-2bc58e928508

**Comment by thomashin** [comment]
I have used this json file: https://chainid.network/chains.json (from https://chainid.network)

**Comment by thomashin** [comment]
also need to check chainid duplication (router `operators.js`)
