### ISSUE TITLE
Error message improvement

### ISSUE THREAD

**Issue by ggs134** [Onther-Tech/dashboard.tokamak.network#6]
![image](https://user-images.githubusercontent.com/8215282/76561294-5e906b00-64e6-11ea-9f35-91eb0b609325.png)

If user tried to connect to dashboard.tokamak.network with `improper network`, then error message should be more clear.

**Comment by thomashin** [comment]
![image](https://user-images.githubusercontent.com/20399507/76580864-c198f680-6514-11ea-921b-34fcb3fab629.png)

**Comment by thomashin** [comment]
block user beforehand
```javascript
hasCorrectNetwork () {
  if (typeof window.ethereum === 'undefined') {
    this.message = 'Please install metamask extension';
    return false;
  }
  if (window.ethereum.networkVersion !== '1337') {
    this.message = 'Please connect to the Faraday Network';
    return false;
  }
  return true;
},
```

**Comment by thomashin** [comment]
I think we need other stuffs
1. web design (optional)
2. guide to connect faraday network (metamask)

**Comment by thomashin** [comment]
`Returned values aren't valid ...` error occurs when we call contract function that not yet deployed on blockchain

**Comment by ggs134** [comment]
Moved to https://github.com/Onther-Tech/dashboard.tokamak.network/issues/15
