### ISSUE TITLE
API server domain set and support `network` parameter.

### ISSUE THREAD

**Issue by sifnoc** [Onther-Tech/dashboard.tokamak.network#60]
- [x] Set domain as `https://dashboard-api.tokamak.network`
- [x] Support `network` parameter likes `https://dashboard-api.tokamak.network/managers?network=rinkeby`

Result will be

- without `network` parameter, serve mainnet data.
- with `network` parameter, serve specific network, i.e rinkeby.

https://dashboard-api.tokamak.network/managers
https://dashboard-api.tokamak.network/managers?network=rinkeby

**Comment by thomashin** [comment]
need to edit `networks=rinkeby` -> `network=rinkeby`

**Comment by sifnoc** [comment]
> need to edit `networks=rinkeby` -> `network=rinkeby`

Updated.

**Comment by thomashin** [comment]
rinkeby db,
mainnet db, 
-> adapter

**Comment by thomashin** [comment]
- npm run server (mainnet)
- npm run server rinkeby
- npm run server development

**Comment by sifnoc** [comment]
I think it is up to you.

I am waiting for API server response like [this](https://github.com/Onther-Tech/docs.tokamak.network/blob/master/website/translated_docs/ko/guides/getting-started/how-to-test-ton-stake-mainnet.md#mton-%EC%BB%A8%ED%8A%B8%EB%9E%99%ED%8A%B8-%EC%A0%95%EB%B3%B4)

```
"TON": "0xe3a87a9343d262f5f11280058ae807b45aa34669",
"WTON": "0x57b7D965082CB6015a89AE1E7df18231A39e1a30",
"RootChainRegistry": "0x5C7F8e605dC7B276a501A27EBc1de756c206c333",
"DepositManager": "0xB993793d7a3641b8b7A099D0D2D7ae8A36F849FC",
"SeigManager": "0x53B9d6c605B27FFDFea787566f21F776c0197805",
"PowerTON": "0x21CDEDEF641Ea65F5BF7e0A0031b20647BD9d0eD"
```

**Comment by thomashin** [comment]
https://docs.google.com/presentation/d/1fUNV-FKPyYe8XLQvCONoFizIyuHRx0SBnPET3jku290/edit?usp=sharing
