### ISSUE TITLE
Manual Commit Feature Required

### ISSUE THREAD

**Issue by ggs134** [Onther-Tech/dashboard.tokamak.network#82]
If current metamask account is operator, manual commit button appeared.
It directly makes `commit transaction` without plasma-evm client support.

![image](https://user-images.githubusercontent.com/8215282/81958929-a7c97c00-9649-11ea-9925-9639fe43fa62.png)

**Comment by thomashin** [comment]
only `submitNRE` can be used for MTON version (so that operator can make commits without running client.)
